### ISSUE TITLE
Incompatible Spring Cloud version in dependency management

### ISSUE THREAD

**Issue by ztomic** [adorsys/xs2a-adapter#202]
Hi,

in [pom.xml](https://github.com/adorsys/xs2a-adapter/blob/develop/pom.xml#L77) Spring Cloud version is Finchley.SR2 and Spring Boot is 2.1.1.RELEASE. Please note that Finchley is not fully compatible with Spring Boot 2.1.x. You should consider upgrading to Greenwich release train of Spring Cloud (see https://spring.io/projects/spring-cloud).

Regards

**Comment by spetrychenko** [comment]
Thanks for your comment. We will fix it in the next release

Best

**Comment by spetrychenko** [comment]
Changes already in the develop branch, thanks for your interest to our project
