### ISSUE TITLE
Validation errors supplied by Xs2a-adapter

### ISSUE THREAD

**Issue by valb3r** [adorsys/xs2a-adapter#348]
**Preface:**
In order to accomplish Open-banking issue:
https://github.com/adorsys/open-banking-gateway/issues/285
Open-banking needs to get list of validation errors for endpoint call - i.e. what RequestHeaders are missing for
As example, we can look at FiduciaAccountInformationService:
```
public Response<TransactionsReport> getTransactionList(String accountId, RequestHeaders requestHeaders, RequestParams requestParams) {
        if (this.notSupportedBookingStatus(requestParams)) {
            throw new BadRequestException(BOOKING_STATUS_ERROR_MESSAGE);
        } else {
            return super.getTransactionList(accountId, requestHeaders, requestParams);
        }
    }
```
Instead of catching exceptions one-by-one open-banking needs List of validation errors:
List(ValidationError((fieldName) "bookingStatus", (errorCode) "unmappable", "ASPSP supports only the following booking statuses..."), ...

We need either:
-  (Preferred) An interface that returns validation errors for request:
Interface like this:
```
interface AccountInformationValidationService  {
...
public List<ValidationErrors> getTransactionList(String accountId, RequestHeaders requestHeaders, RequestParams requestParams);
...
}
```
That returns something like 
List(ValidationError((fieldName) "bookingStatus", (errorCode) "unmappable", "ASPSP supports only the following booking statuses..."), ...
-  (Less good) Exception that contains the list of validation issues (list is same as above ideally)

**Comment by jonnyfoka** [comment]
Hi @valb3r , after analysing your request we came with following proposal. Please get back to us, if further discussion is needed. 

<img width="1007" alt="grafik" src="https://user-images.githubusercontent.com/28448798/75437181-1d308500-5956-11ea-9d03-49319aeae02a.png">
<img width="1122" alt="grafik" src="https://user-images.githubusercontent.com/28448798/75437198-2588c000-5956-11ea-9cb3-99ea2082af97.png">

**Comment by markramercado** [comment]
Hi @valb3r , after analysing your request we came with following proposal. Please get back to us if further discussions are needed. 

<img width="1008" alt="grafik" src="https://user-images.githubusercontent.com/49722751/75437440-7bf5fe80-5956-11ea-9951-b522403b85a5.png">
<img width="1096" alt="grafik" src="https://user-images.githubusercontent.com/49722751/75437467-831d0c80-5956-11ea-9a4a-d25d432dbe49.png">

**Comment by valb3r** [comment]
@markramercado I'm fine with it, but InvalidItem code field should be some ENUM, not string

**Comment by artemsnisarenko** [comment]
@valb3r please have a look at the PR
