### ISSUE TITLE
Extend adapter interface to support Encoded Words for some http-header values

### ISSUE THREAD

**Issue by francis-pouatcha** [adorsys/xs2a-adapter#364]
For all header value, the Adapter shall be able to parse value sent in encoded word format. This will help process some extended characters for fields like PSU-ID and PSU-CORPORATE-ID. See: 
 https://en.wikipedia.org/wiki/MIME#Encoded-Word

**Comment by spetrychenko** [comment]
Hi @francis-pouatcha , already implemented and pushed to the develop branch and will be released next week.

**Comment by spetrychenko** [comment]
The fix is available with the adapter version `0.0.8`. Please use it to get this functionality.
