### ISSUE TITLE
Adorsys integ adapter request signing

### ISSUE THREAD

**Issue by valb3r** [adorsys/xs2a-adapter#367]
Adorsys XS2A integ adapter needs to support request signing and passing the QWAC public certificate to XS2A-Dynamic Sandbox

**Comment by artemsnisarenko** [comment]
https://github.com/adorsys/xs2a-adapter/pull/373

**Comment by spetrychenko** [comment]
Hi @valb3r, the fix already merged into develop. We planning to have the release this week.

**Comment by spetrychenko** [comment]
@valb3r The fix is available with the adapter version 0.0.8.
