### ISSUE TITLE
support EMAIL scaMethod

### ISSUE THREAD

**Issue by max402** [adorsys/xs2a-adapter#521]
Class AuthenticationObject up to version 0.0.11 had field String authenticationType and sandbox could use different [scaMethods](https://github.com/adorsys/XS2A-Sandbox/blob/master/tpp-ui/src/app/models/scaMethods.ts).
From version 0.1.0 field authenticationType is [enum](https://github.com/adorsys/xs2a-adapter/blob/develop/xs2a-adapter-generated-api/src/main/java/de/adorsys/xs2a/adapter/api/model/AuthenticationType.java) with only available values: SMS_OTP, CHIP_OTP, PHOTO_OTP, PUSH_OTP. 
Widely used by Sandbox value EMAIL can't be used anymore.
This error blocks OBG from updatating to new version of XS2A-Adapter.
Please return possibility to use custom authentication type.

**Comment by berezkin88** [comment]
support for EMAIL is added in version 0.1.4

**Comment by max402** [comment]
Thank you. It should work now.
I've noticed that there is new version of [psd2-api 1.3.8 2020-11-18v1.yaml](https://77cb457b-3353-4bdc-8ab6-ff6bb2ccdc98.filesusr.com/archives/c2914b_664f2e9dfd624507af82fa9abe2af8e7.zip?dn=psd2-api%201.3.8%202020-11-18v1.yaml.zip). They added SMTP_OTP. Probably would be good to follow names from specification. Of course then it requires also changes in Sandbox.

**Comment by berezkin88** [comment]
No problem.
And yes, you are right. Adapter will update its models in future releases to comfort new BG specifications. EMAIL will be replaced with SMTP_OTP. It will be mentioned in Release Notes so you will be aware of changes.
