### ISSUE TITLE
Transaction list in latest Sandbox seem to be no more functional

### ISSUE THREAD

**Issue by valb3r** [adorsys/xs2a-adapter#531]
In the latest Sandbox, according to NextGen PSD2 [v1.3.6 YAML](https://berlingroup.stackstorage.com/s/1FBrOlC7IquzG35B) 
remittanceInformationStructured has changed:
`Changed types of remittance information structured properties in SpiTransaction and SpiSinglePayment`
https://github.com/adorsys/xs2a-connector-examples/releases/tag/7.9

This causes the impossibility to use xs2a-adapter with the latest Sandbox.

Current dev still references old remittanceInformationStructured types:
https://github.com/adorsys/xs2a-adapter/blob/develop/xs2a-adapter-generated-api/src/main/java/de/adorsys/xs2a/adapter/api/model/RemittanceInformationStructured.java

**Comment by berezkin88** [comment]
Models were updated to align with BG v1.3.6 in Adapter version 0.1.4
