### ISSUE TITLE
sparkasse-adapter getTransactionList error

### ISSUE THREAD

**Issue by max402** [adorsys/xs2a-adapter#612]
Sparkasse returns on getTransactionList with Accept header "application/json"

`{"tppMessages":[{"category":"ERROR","code":"REQUESTED_FORMATS_INVALID","text":"The requested formats in the Accept header entry are not matching the formats offered by the ASPSP."}]}`

Wenn getTransactionListAsString is used then Accept header not set and it works, but returns body in xml format.

Even in sparkasse-stubs response has xml body. 
https://github.com/adorsys/xs2a-adapter/blob/develop/adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-get-transactions.json

**Comment by berezkin88** [comment]
Currently, Sparkasse returns a list of transactions in XML format only. The adapter is treating XML as a mere Object and passes data as is, without converting or mapping.

An XML mapping feature will be added to the Roadmap.

**Comment by gatiskalnins** [comment]
We discussed it internally and decided to develop the mapper in OBG under ticket https://jira.adorsys.de/browse/OBG-34. Therefore there won't be a need to have it in XS2A Adapter as long as the Adapter passes the information to OBG.

**Comment by berezkin88** [comment]
I see. I believe this issue is safe to close.
